---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: python-app:v10
        envFrom:
          - configMapRef:
              name: demo-config
        command: ["/bin/sh"]
        args: ["-c", "nohup redis-server & > /dev/null 2>&1 && python ./hello.py"]
        ports:
        - containerPort: 8000
        resources:
          requests:
              memory: 100Mi
              cpu: "0.25"
          limits:
              memory: 400Mi
              cpu: "1"